//:: Login Actions
export const LOGIN_BEGIN = 'LOGIN_BEGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const RECONNECT_BEGIN = 'RECONNECT_BEGIN'
export const RECONNECT_SUCCESS = 'RECONNECT_SUCCESS'
export const RECONNECT_FAILURE = 'RECONNECT_FAILURE'

export const LOGOUT = 'LOGOUT'

//:: Register User
export const POST_REGISTER_USER_BEGIN = 'POST_REGISTER_USER_BEGIN'
export const POST_REGISTER_USER_SUCCESS = 'POST_REGISTER_USER_SUCCESS'
export const POST_REGISTER_USER_FAILURE = 'POST_REGISTER_USER_FAILURE'

//:: Product Actions
export const GET_PROJECTS_BEGIN = 'GET_PROJECTS_BEGIN'
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS'
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE'

export const POST_PROJECTS_BEGIN = 'POST_PROJECTS_BEGIN'
export const POST_PROJECTS_SUCCESS = 'POST_PROJECTS_SUCCESS'
export const POST_PROJECTS_FAILURE = 'POST_PROJECTS_FAILURE'

export const DELETE_PROJECTS_BEGIN = 'DELETE_PROJECTS_BEGIN'
export const DELETE_PROJECTS_SUCCESS = 'DELETE_PROJECTS_SUCCESS'
export const DELETE_PROJECTS_FAILURE = 'DELETE_PROJECTS_FAILURE'

export const PUT_PROJECTS_BEGIN = 'PUT_PROJECTS_BEGIN'
export const PUT_PROJECTS_SUCCESS = 'PUT_PROJECTS_SUCCESS'
export const PUT_PROJECTS_FAILURE = 'PUT_PROJECTS_FAILURE'

//:: Product Tasks Actions
export const GET_PROJECT_TASKS_BEGIN = 'GET_PROJECT_TASKS_BEGIN'
export const GET_PROJECT_TASKS_SUCCESS = 'GET_PROJECT_TASKS_SUCCESS'
export const GET_PROJECT_TASKS_FAILURE = 'GET_PROJECT_TASKS_FAILURE'

export const POST_TASK_BEGIN = 'POST_TASK_BEGIN'
export const POST_TASK_SUCCESS = 'POST_TASK_SUCCESS'
export const POST_TASK_FAILURE = 'POST_TASK_FAILURE'

export const DELETE_TASK_BEGIN = 'DELETE_TASK_BEGIN'
export const DELETE_TASK_SUCCESS = 'DELETE_TASK_SUCCESS'
export const DELETE_TASK_FAILURE = 'DELETE_TASK_FAILURE'

export const PUT_TASK_BEGIN = 'PUT_TASK_BEGIN'
export const PUT_TASK_SUCCESS = 'PUT_TASK_SUCCESS'
export const PUT_TASK_FAILURE = 'PUT_TASK_FAILURE'

export const PUT_FINISH_TASK_BEGIN = 'PUT_FINISH_TASK_BEGIN'
export const PUT_FINISH_TASK_SUCCESS = 'PUT_FINISH_TASK_SUCCESS'
export const PUT_FINISH_TASK_FAILURE = 'PUT_FINISH_TASK_FAILURE'